from app.modules.media_attributes.constants import MediaAttributeKey
from app.modules.media_attributes.models import MediaAttributeModel
from app.modules.preferences.constants import PreferenceKey

DEFAULT_ATTRIBUTES = [
    # Languages
    MediaAttributeModel(
        id=MediaAttributeKey.HUN,
        name="magyar",
        short_name="Hun",
        preference_id=PreferenceKey.LANGUAGE,
        pattern=r"\b(hun(?:[-_. ]?dub)?|magyar|hungarian)\b",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.ENG,
        name="angol",
        short_name="Eng",
        preference_id=PreferenceKey.LANGUAGE,
        pattern=r"\b(eng(?:[-_. ]?dub)?|english)\b",
    ),
    # Resolutions
    MediaAttributeModel(
        id=MediaAttributeKey.R2160P,
        name="UHD (4K)",
        short_name=None,
        preference_id=PreferenceKey.RESOLUTION,
        pattern=r"(2160p|4k[-_. ](?:UHD|HEVC|BD)|(?:UHD|HEVC|BD)[-_. ]4k|\b(4k)\b|COMPLETE.UHD|UHD.COMPLETE)",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.R1080P,
        name="Full HD (1080p)",
        short_name=None,
        preference_id=PreferenceKey.RESOLUTION,
        pattern=r"(1080(i|p)|1920x1080)(10bit)?",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.R720P,
        name="HD (720p)",
        short_name=None,
        preference_id=PreferenceKey.RESOLUTION,
        pattern=r"(720(i|p)|1280x720|960p)(10bit)?",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.R576P,
        name="SD (576p)",
        short_name=None,
        preference_id=PreferenceKey.RESOLUTION,
        pattern=r"(576(i|p))",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.R540P,
        name="SD (540p)",
        short_name=None,
        preference_id=PreferenceKey.RESOLUTION,
        pattern=r"(540(i|p))",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.R480P,
        name="SD (480p)",
        short_name=None,
        preference_id=PreferenceKey.RESOLUTION,
        pattern=r"(480(i|p)|640x480|848x480)",
    ),
    # Video Qualities
    MediaAttributeModel(
        id=MediaAttributeKey.DV,
        name="Dolby Vision",
        preference_id=PreferenceKey.VIDEO_QUALITY,
        pattern=r"\b(dolby[-_. ]?vision|dovi|dv)\b",
        short_name=None,
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.HDR10P,
        name="HDR10+",
        preference_id=PreferenceKey.VIDEO_QUALITY,
        pattern=r"(?<![a-zA-Z0-9])(hdr10(?:plus|p|\+))(?![a-zA-Z0-9])",
        short_name=None,
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.HDR10,
        name="HDR10",
        preference_id=PreferenceKey.VIDEO_QUALITY,
        pattern=r"(?<![a-zA-Z0-9])(hdr(?:10)?)(?![a-zA-Z0-9+])",
        short_name=None,
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.HLG,
        name="HLG",
        preference_id=PreferenceKey.VIDEO_QUALITY,
        pattern=r"\b(hlg)\b",
        short_name=None,
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.SDR,
        name="SDR",
        preference_id=PreferenceKey.VIDEO_QUALITY,
        pattern=None,
        short_name=None,
        show_in_details=False,
    ),
    # Video Codecs
    MediaAttributeModel(
        id=MediaAttributeKey.AV1,
        name="AV1",
        preference_id=PreferenceKey.VIDEO_CODEC,
        pattern=r"\b(av1)\b",
        short_name="AV1",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.X265,
        name="x265 (HEVC)",
        preference_id=PreferenceKey.VIDEO_CODEC,
        pattern=r"\b(x265|h\.?265|hevc)\b",
        short_name="x265",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.X264,
        name="x264 (AVC)",
        preference_id=PreferenceKey.VIDEO_CODEC,
        pattern=r"\b(x264|h\.?264|avc)\b",
        short_name="x264",
    ),
    # Sources
    MediaAttributeModel(
        id=MediaAttributeKey.REMUX,
        name="Remux",
        preference_id=PreferenceKey.SOURCE,
        pattern=r"\b(remux)\b",
        short_name="Remux",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.UHD,
        name="UHD",
        preference_id=PreferenceKey.SOURCE,
        pattern=r"\b(uhd)\b",
        short_name=None,
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.BLURAY,
        name="Blu-ray",
        preference_id=PreferenceKey.SOURCE,
        pattern=r"\b(blu[-_. ]?ray)\b",
        short_name="Blu-ray",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.BDRIP,
        name="BDRip",
        preference_id=PreferenceKey.SOURCE,
        pattern=r"\b(bdrip)\b",
        short_name="BDRip",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.WEB_DL,
        name="Web-DL",
        preference_id=PreferenceKey.SOURCE,
        pattern=r"\b(web[-_. ]?dl|web(?![-_. ]?rip))\b",
        short_name=None,
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.WEB_RIP,
        name="WebRip",
        preference_id=PreferenceKey.SOURCE,
        pattern=r"\b(webrip|web[-_. ]rip)\b",
        short_name=None,
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.DVD_RIP,
        name="DVD Rip",
        preference_id=PreferenceKey.SOURCE,
        pattern=r"\b(dvdrip)\b",
        short_name="DVDRip",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.HDTV,
        name="TV Rip",
        preference_id=PreferenceKey.SOURCE,
        pattern=r"\b(hdtv|pdtv|dvb|satrip)\b",
        short_name="HDTV",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.CAM,
        name="Cam",
        preference_id=PreferenceKey.SOURCE,
        pattern=r"\b(cam|hdcam|ts|telesync|scr|dvdscr|md|mdhun|mdub)\b",
        short_name=None,
    ),
    # Edition
    MediaAttributeModel(
        id=MediaAttributeKey.THEATRICAL,
        name="Moziváltozat (Theatrical)",
        preference_id=PreferenceKey.EDITION,
        pattern=None,
        short_name="Theatrical",
        show_in_details=False,
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.UNCUT,
        name="Vágatlan változat (Uncut / Unrated)",
        preference_id=PreferenceKey.EDITION,
        pattern=r"\b(unrated|uncut)\b",
        short_name="Uncut",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.REMASTERED,
        name="Felújított változat (Remastered)",
        preference_id=PreferenceKey.EDITION,
        pattern=r"\b(remastered)\b",
        short_name="Remastered",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.EXTENDED,
        name="Bővített változat (Extended Cut)",
        preference_id=PreferenceKey.EDITION,
        pattern=r"\b(extended(?:[-_. ]?cut)?)\b",
        short_name="Extended",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.DIRECTORS_CUT,
        name="Rendezői változat (Director's Cut)",
        preference_id=PreferenceKey.EDITION,
        pattern=r"\b(dc|directors?[-_. ]?cut|final[-_. ]?cut)\b",
        short_name="Director's Cut",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.SPECIAL_EDITION,
        name="Speciális kiadás (Special Edition)",
        preference_id=PreferenceKey.EDITION,
        pattern=r"\b(special[-_. ]?edition|assembly[-_. ]?cut)\b",
        short_name="Special Edition",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.OPEN_MATTE,
        name="Open Matte (teljes képkivágás)",
        preference_id=PreferenceKey.EDITION,
        pattern=r"\b(open[-_. ]?matte)\b",
        short_name="Open Matte",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.COLLECTORS_EDITION,
        name="Gyűjtői kiadás (Collector's Edition)",
        preference_id=PreferenceKey.EDITION,
        pattern=r"\b(collectors?[-_. ]?edition)\b",
        short_name="Collector's Edition",
        is_preferable=False,
        show_in_details=True,
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.LIMITED_EDITION,
        name="Limitált kiadás (Limited Edition)",
        preference_id=PreferenceKey.EDITION,
        pattern=r"\b(limited[-_. ]?edition)\b",
        short_name="Limited Edition",
        is_preferable=False,
        show_in_details=True,
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.ULTIMATE_EDITION,
        name="Teljes kiadás (Ultimate Edition)",
        preference_id=PreferenceKey.EDITION,
        pattern=r"\b(ultimate[-_. ]?edition)\b",
        short_name="Ultimate Edition",
        is_preferable=False,
        show_in_details=True,
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.DEFINITIVE_EDITION,
        name="Végleges kiadás (Definitive Edition)",
        preference_id=PreferenceKey.EDITION,
        pattern=r"\b(definitive[-_. ]?edition)\b",
        short_name="Definitive Edition",
        is_preferable=False,
        show_in_details=True,
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.ANNIVERSARY_EDITION,
        name="Évfordulós kiadás (Anniversary Edition)",
        preference_id=PreferenceKey.EDITION,
        pattern=r"\b(anniversary[-_. ]?edition)\b",
        short_name="Anniversary Edition",
        is_preferable=False,
        show_in_details=True,
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.IMAX,
        name="IMAX verzió",
        preference_id=PreferenceKey.EDITION,
        pattern=r"\b(imax)\b",
        short_name="IMAX",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.BLACK_AND_WHITE,
        name="Fekete-Fehér (Black and White)",
        preference_id=PreferenceKey.EDITION,
        pattern=r"\.bw\.",
        short_name="Black and White",
        is_preferable=False,
        show_in_details=True,
    ),
    # Audio Qualities
    MediaAttributeModel(
        id=MediaAttributeKey.TRUEHD,
        name="Dolby TrueHD",
        preference_id=PreferenceKey.AUDIO_QUALITY,
        pattern=r"\b(truehd)\b",
        short_name="TrueHD",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.DTS_HD_MA,
        name="DTS-HD Master Audio",
        preference_id=PreferenceKey.AUDIO_QUALITY,
        pattern=r"\b(dts[-_. ]?hd(?:[-_. ]?(?:ma|hra))?|dtshd(?:ma|hra)?)\b",
        short_name="DTS-HD MA",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.FLAC,
        name="FLAC",
        preference_id=PreferenceKey.AUDIO_QUALITY,
        pattern=r"\b(flac)\b",
        short_name=None,
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.DD_PLUS,
        name="Dolby Digital Plus",
        preference_id=PreferenceKey.AUDIO_QUALITY,
        pattern=r"\b(ddp[-_. ]?(?:2\.0|5\.1|7\.1)?|dd\+[-_. ]?(?:2\.0|5\.1|7\.1)?|e[-_. ]?ac[-_. ]?3)(?!\w)",
        short_name=None,
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.DTS,
        name="DTS",
        preference_id=PreferenceKey.AUDIO_QUALITY,
        pattern=r"\b(dts(?:[-_. ]?es)?(?![-_. ]?(?:hd|x)))\b",
        short_name=None,
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.DD,
        name="Dolby Digital",
        preference_id=PreferenceKey.AUDIO_QUALITY,
        pattern=r"\b(dd(?!p|\+)[-_. ]?(?:2\.0|5\.1|7\.1)?|ac[-_. ]?3)\b",
        short_name=None,
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.AAC,
        name="AAC / MP3",
        preference_id=PreferenceKey.AUDIO_QUALITY,
        pattern=r"\b(aac[-_. ]?(?:2\.0|5\.1)?|mp3)\b",
        short_name="AAC",
    ),
    # Audio Spatials
    MediaAttributeModel(
        id=MediaAttributeKey.DTS_X,
        name="DTS:X",
        preference_id=PreferenceKey.AUDIO_SPATIAL,
        pattern=r"\b(dts[-_. ]?x|dtsx)\b",
        short_name=None,
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.DOLBY_ATMOS,
        name="Dolby Atmos",
        preference_id=PreferenceKey.AUDIO_SPATIAL,
        pattern=r"\b(atmos)\b",
        short_name=None,
    ),
    # Audio Channels
    MediaAttributeModel(
        id=MediaAttributeKey.CH_7_1,
        name="7.1 (Bővített térhangzás)",
        preference_id=PreferenceKey.AUDIO_CHANNELS,
        pattern=r"(7\.1|7ch)",
        short_name="7.1",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.CH_5_1,
        name="5.1 (Térhangzás)",
        preference_id=PreferenceKey.AUDIO_CHANNELS,
        pattern=r"(5\.1|6ch)",
        short_name="5.1",
    ),
    MediaAttributeModel(
        id=MediaAttributeKey.CH_2_0,
        name="2.0 (Sztereó)",
        preference_id=PreferenceKey.AUDIO_CHANNELS,
        pattern=r"(2\.0|2ch|stereo)",
        short_name="2.0",
    ),
    # Others
    MediaAttributeModel(
        id=MediaAttributeKey.THREE_D,
        name="3D",
        preference_id=None,
        pattern=r"\b(3d|hsbs|hou|half[-_. ]?(?:sbs|ou))\b",
        short_name="3D",
    ),
]
